/**
 * DLF Westpark Phase 1 — floor & configuration data.
 * GENERATED by scripts/export_dlf_plans.py from seed_dlf_brochure_extraction.py
 * (source: visual review of the official brochure, Presenter 1.pdf). Do not hand-edit.
 * Plate→floor mapping (typical/refuge/fl36/duplex) inferred from brochure page order;
 * flag any mismatch to the operator.
 */

export const dlfProject = {
  name: "DLF The Westpark – Phase 1",
  rera: "PR1181012500079",
  developer: "Peegen Builders and Developers Pvt. Ltd. (DLF + Trident Realty)",
  towers: ["T02", "T03", "T04", "T05"],
} as const;

export interface DlfConfig {
  id: string;
  unit: string;
  label: string;
  carpetSqft: number;
  balconySqft: number;
  totalSqft: number;
  floors: string;
  planImage: string;
}

export interface DlfFloor {
  n: number;
  kind: "typical" | "refuge" | "refuge-variant" | "duplex";
  plate: string | null;
  configs: string[];
}

export interface DlfTower {
  id: string;
  name: string;
  floorCount: number;
  configs: DlfConfig[];
  floors: DlfFloor[];
}

export const dlfTowers: DlfTower[] = [
  {
    id: "T02",
    name: "Tower-02",
    floorCount: 40,
    configs: [
      {id: "T02-3BHK-01", unit: "01", label: "3 BHK", carpetSqft: 1260.72, balconySqft: 103.99, totalSqft: 1364.71, floors: "3–6, 8–12, 14, 16–21, 23–28, 30–35", planImage: "/dlf/t02-3bhk-01-floor_plan-p11.jpg"},
      {id: "T02-3BHK-02", unit: "02", label: "3 BHK", carpetSqft: 1260.72, balconySqft: 103.99, totalSqft: 1364.71, floors: "3–6, 8–12, 14, 16–21, 23–28, 30–35", planImage: "/dlf/t02-3bhk-01-floor_plan-p11.jpg"},
      {id: "T02-5BHK-01", unit: "01", label: "5 BHK", carpetSqft: 1825.23, balconySqft: 175.69, totalSqft: 2000.92, floors: "7, 15, 22, 29", planImage: "/dlf/t02-5bhk-01-floor_plan-p13.jpg"},
      {id: "T02-4BHK-01", unit: "01", label: "4 BHK", carpetSqft: 2136.46, balconySqft: 175.69, totalSqft: 2312.15, floors: "36, 37, 38", planImage: "/dlf/t02-4bhk-01-floor_plan-p12.jpg"},
      {id: "T02-4BHK-DUPLEX-01", unit: "01", label: "4 BHK Duplex", carpetSqft: 2087.62, balconySqft: 162.08, totalSqft: 2249.71, floors: "39 (lower) + 40 (upper)", planImage: "/dlf/t02-4bhk-duplex-01-floor_plan-p14.jpg"}
    ],
    floors: [
      {n: 3, kind: "typical", plate: "/dlf/t02-floor_plan-p6.jpg", configs: ["T02-3BHK-01", "T02-3BHK-02"]},
      {n: 4, kind: "typical", plate: "/dlf/t02-floor_plan-p6.jpg", configs: ["T02-3BHK-01", "T02-3BHK-02"]},
      {n: 5, kind: "typical", plate: "/dlf/t02-floor_plan-p6.jpg", configs: ["T02-3BHK-01", "T02-3BHK-02"]},
      {n: 6, kind: "typical", plate: "/dlf/t02-floor_plan-p6.jpg", configs: ["T02-3BHK-01", "T02-3BHK-02"]},
      {n: 7, kind: "refuge-variant", plate: "/dlf/t02-floor_plan-p7.jpg", configs: ["T02-5BHK-01"]},
      {n: 8, kind: "typical", plate: "/dlf/t02-floor_plan-p6.jpg", configs: ["T02-3BHK-01", "T02-3BHK-02"]},
      {n: 9, kind: "typical", plate: "/dlf/t02-floor_plan-p6.jpg", configs: ["T02-3BHK-01", "T02-3BHK-02"]},
      {n: 10, kind: "typical", plate: "/dlf/t02-floor_plan-p6.jpg", configs: ["T02-3BHK-01", "T02-3BHK-02"]},
      {n: 11, kind: "typical", plate: "/dlf/t02-floor_plan-p6.jpg", configs: ["T02-3BHK-01", "T02-3BHK-02"]},
      {n: 12, kind: "typical", plate: "/dlf/t02-floor_plan-p6.jpg", configs: ["T02-3BHK-01", "T02-3BHK-02"]},
      {n: 13, kind: "refuge", plate: null, configs: []},
      {n: 14, kind: "typical", plate: "/dlf/t02-floor_plan-p6.jpg", configs: ["T02-3BHK-01", "T02-3BHK-02"]},
      {n: 15, kind: "refuge-variant", plate: "/dlf/t02-floor_plan-p7.jpg", configs: ["T02-5BHK-01"]},
      {n: 16, kind: "typical", plate: "/dlf/t02-floor_plan-p6.jpg", configs: ["T02-3BHK-01", "T02-3BHK-02"]},
      {n: 17, kind: "typical", plate: "/dlf/t02-floor_plan-p6.jpg", configs: ["T02-3BHK-01", "T02-3BHK-02"]},
      {n: 18, kind: "typical", plate: "/dlf/t02-floor_plan-p6.jpg", configs: ["T02-3BHK-01", "T02-3BHK-02"]},
      {n: 19, kind: "typical", plate: "/dlf/t02-floor_plan-p6.jpg", configs: ["T02-3BHK-01", "T02-3BHK-02"]},
      {n: 20, kind: "typical", plate: "/dlf/t02-floor_plan-p6.jpg", configs: ["T02-3BHK-01", "T02-3BHK-02"]},
      {n: 21, kind: "typical", plate: "/dlf/t02-floor_plan-p6.jpg", configs: ["T02-3BHK-01", "T02-3BHK-02"]},
      {n: 22, kind: "refuge-variant", plate: "/dlf/t02-floor_plan-p7.jpg", configs: ["T02-5BHK-01"]},
      {n: 23, kind: "typical", plate: "/dlf/t02-floor_plan-p6.jpg", configs: ["T02-3BHK-01", "T02-3BHK-02"]},
      {n: 24, kind: "typical", plate: "/dlf/t02-floor_plan-p6.jpg", configs: ["T02-3BHK-01", "T02-3BHK-02"]},
      {n: 25, kind: "typical", plate: "/dlf/t02-floor_plan-p6.jpg", configs: ["T02-3BHK-01", "T02-3BHK-02"]},
      {n: 26, kind: "typical", plate: "/dlf/t02-floor_plan-p6.jpg", configs: ["T02-3BHK-01", "T02-3BHK-02"]},
      {n: 27, kind: "typical", plate: "/dlf/t02-floor_plan-p6.jpg", configs: ["T02-3BHK-01", "T02-3BHK-02"]},
      {n: 28, kind: "typical", plate: "/dlf/t02-floor_plan-p6.jpg", configs: ["T02-3BHK-01", "T02-3BHK-02"]},
      {n: 29, kind: "refuge-variant", plate: "/dlf/t02-floor_plan-p7.jpg", configs: ["T02-5BHK-01"]},
      {n: 30, kind: "typical", plate: "/dlf/t02-floor_plan-p6.jpg", configs: ["T02-3BHK-01", "T02-3BHK-02"]},
      {n: 31, kind: "typical", plate: "/dlf/t02-floor_plan-p6.jpg", configs: ["T02-3BHK-01", "T02-3BHK-02"]},
      {n: 32, kind: "typical", plate: "/dlf/t02-floor_plan-p6.jpg", configs: ["T02-3BHK-01", "T02-3BHK-02"]},
      {n: 33, kind: "typical", plate: "/dlf/t02-floor_plan-p6.jpg", configs: ["T02-3BHK-01", "T02-3BHK-02"]},
      {n: 34, kind: "typical", plate: "/dlf/t02-floor_plan-p6.jpg", configs: ["T02-3BHK-01", "T02-3BHK-02"]},
      {n: 35, kind: "typical", plate: "/dlf/t02-floor_plan-p6.jpg", configs: ["T02-3BHK-01", "T02-3BHK-02"]},
      {n: 36, kind: "typical", plate: "/dlf/t02-floor_plan-p8.jpg", configs: ["T02-4BHK-01"]},
      {n: 37, kind: "typical", plate: "/dlf/t02-floor_plan-p8.jpg", configs: ["T02-4BHK-01"]},
      {n: 38, kind: "typical", plate: "/dlf/t02-floor_plan-p8.jpg", configs: ["T02-4BHK-01"]},
      {n: 39, kind: "duplex", plate: "/dlf/t02-floor_plan-p9.jpg", configs: ["T02-4BHK-DUPLEX-01"]},
      {n: 40, kind: "duplex", plate: "/dlf/t02-floor_plan-p10.jpg", configs: ["T02-4BHK-DUPLEX-01"]}
    ],
  },
  {
    id: "T03",
    name: "Tower-03",
    floorCount: 40,
    configs: [
      {id: "T03-3BHK-01", unit: "01", label: "3 BHK", carpetSqft: 1255.29, balconySqft: 103.99, totalSqft: 1359.28, floors: "3–12, 14–38", planImage: "/dlf/t03-3bhk-01-floor_plan-p20.jpg"},
      {id: "T03-3BHK-02", unit: "02", label: "3 BHK", carpetSqft: 1255.29, balconySqft: 103.99, totalSqft: 1359.28, floors: "3–12, 14–38", planImage: "/dlf/t03-3bhk-01-floor_plan-p20.jpg"},
      {id: "T03-3BHK-03", unit: "03", label: "3 BHK", carpetSqft: 1048.07, balconySqft: 78.33, totalSqft: 1126.4, floors: "3–12, 14–35, 37–39", planImage: "/dlf/t03-3bhk-03-floor_plan-p21.jpg"},
      {id: "T03-3BHK-04", unit: "04", label: "3 BHK", carpetSqft: 1048.07, balconySqft: 78.33, totalSqft: 1126.4, floors: "3–6, 8–11, 14, 16–21, 23–28, 30–35, 37–39", planImage: "/dlf/t03-3bhk-03-floor_plan-p21.jpg"},
      {id: "T03-4BHK-03", unit: "03", label: "4 BHK", carpetSqft: 1277.5, balconySqft: 78.33, totalSqft: 1355.83, floors: "36", planImage: "/dlf/t03-4bhk-03-floor_plan-p22.jpg"},
      {id: "T03-4BHK-DUPLEX-01", unit: "01", label: "4 BHK Duplex", carpetSqft: 2078.77, balconySqft: 162.08, totalSqft: 2240.85, floors: "39 (lower) + 40 (upper)", planImage: "/dlf/t03-4bhk-duplex-01-floor_plan-p23.jpg"},
      {id: "T03-4BHK-DUPLEX-02", unit: "02", label: "4 BHK Duplex", carpetSqft: 2078.77, balconySqft: 162.08, totalSqft: 2240.85, floors: "39 (lower) + 40 (upper)", planImage: "/dlf/t03-4bhk-duplex-01-floor_plan-p23.jpg"}
    ],
    floors: [
      {n: 3, kind: "typical", plate: "/dlf/t03-floor_plan-p15.jpg", configs: ["T03-3BHK-01", "T03-3BHK-02", "T03-3BHK-03", "T03-3BHK-04"]},
      {n: 4, kind: "typical", plate: "/dlf/t03-floor_plan-p15.jpg", configs: ["T03-3BHK-01", "T03-3BHK-02", "T03-3BHK-03", "T03-3BHK-04"]},
      {n: 5, kind: "typical", plate: "/dlf/t03-floor_plan-p15.jpg", configs: ["T03-3BHK-01", "T03-3BHK-02", "T03-3BHK-03", "T03-3BHK-04"]},
      {n: 6, kind: "typical", plate: "/dlf/t03-floor_plan-p15.jpg", configs: ["T03-3BHK-01", "T03-3BHK-02", "T03-3BHK-03", "T03-3BHK-04"]},
      {n: 7, kind: "refuge-variant", plate: "/dlf/t03-floor_plan-p16.jpg", configs: ["T03-3BHK-01", "T03-3BHK-02", "T03-3BHK-03"]},
      {n: 8, kind: "typical", plate: "/dlf/t03-floor_plan-p15.jpg", configs: ["T03-3BHK-01", "T03-3BHK-02", "T03-3BHK-03", "T03-3BHK-04"]},
      {n: 9, kind: "typical", plate: "/dlf/t03-floor_plan-p15.jpg", configs: ["T03-3BHK-01", "T03-3BHK-02", "T03-3BHK-03", "T03-3BHK-04"]},
      {n: 10, kind: "typical", plate: "/dlf/t03-floor_plan-p15.jpg", configs: ["T03-3BHK-01", "T03-3BHK-02", "T03-3BHK-03", "T03-3BHK-04"]},
      {n: 11, kind: "typical", plate: "/dlf/t03-floor_plan-p15.jpg", configs: ["T03-3BHK-01", "T03-3BHK-02", "T03-3BHK-03", "T03-3BHK-04"]},
      {n: 12, kind: "typical", plate: "/dlf/t03-floor_plan-p15.jpg", configs: ["T03-3BHK-01", "T03-3BHK-02", "T03-3BHK-03"]},
      {n: 13, kind: "refuge", plate: null, configs: []},
      {n: 14, kind: "typical", plate: "/dlf/t03-floor_plan-p15.jpg", configs: ["T03-3BHK-01", "T03-3BHK-02", "T03-3BHK-03", "T03-3BHK-04"]},
      {n: 15, kind: "refuge-variant", plate: "/dlf/t03-floor_plan-p16.jpg", configs: ["T03-3BHK-01", "T03-3BHK-02", "T03-3BHK-03"]},
      {n: 16, kind: "typical", plate: "/dlf/t03-floor_plan-p15.jpg", configs: ["T03-3BHK-01", "T03-3BHK-02", "T03-3BHK-03", "T03-3BHK-04"]},
      {n: 17, kind: "typical", plate: "/dlf/t03-floor_plan-p15.jpg", configs: ["T03-3BHK-01", "T03-3BHK-02", "T03-3BHK-03", "T03-3BHK-04"]},
      {n: 18, kind: "typical", plate: "/dlf/t03-floor_plan-p15.jpg", configs: ["T03-3BHK-01", "T03-3BHK-02", "T03-3BHK-03", "T03-3BHK-04"]},
      {n: 19, kind: "typical", plate: "/dlf/t03-floor_plan-p15.jpg", configs: ["T03-3BHK-01", "T03-3BHK-02", "T03-3BHK-03", "T03-3BHK-04"]},
      {n: 20, kind: "typical", plate: "/dlf/t03-floor_plan-p15.jpg", configs: ["T03-3BHK-01", "T03-3BHK-02", "T03-3BHK-03", "T03-3BHK-04"]},
      {n: 21, kind: "typical", plate: "/dlf/t03-floor_plan-p15.jpg", configs: ["T03-3BHK-01", "T03-3BHK-02", "T03-3BHK-03", "T03-3BHK-04"]},
      {n: 22, kind: "refuge-variant", plate: "/dlf/t03-floor_plan-p16.jpg", configs: ["T03-3BHK-01", "T03-3BHK-02", "T03-3BHK-03"]},
      {n: 23, kind: "typical", plate: "/dlf/t03-floor_plan-p15.jpg", configs: ["T03-3BHK-01", "T03-3BHK-02", "T03-3BHK-03", "T03-3BHK-04"]},
      {n: 24, kind: "typical", plate: "/dlf/t03-floor_plan-p15.jpg", configs: ["T03-3BHK-01", "T03-3BHK-02", "T03-3BHK-03", "T03-3BHK-04"]},
      {n: 25, kind: "typical", plate: "/dlf/t03-floor_plan-p15.jpg", configs: ["T03-3BHK-01", "T03-3BHK-02", "T03-3BHK-03", "T03-3BHK-04"]},
      {n: 26, kind: "typical", plate: "/dlf/t03-floor_plan-p15.jpg", configs: ["T03-3BHK-01", "T03-3BHK-02", "T03-3BHK-03", "T03-3BHK-04"]},
      {n: 27, kind: "typical", plate: "/dlf/t03-floor_plan-p15.jpg", configs: ["T03-3BHK-01", "T03-3BHK-02", "T03-3BHK-03", "T03-3BHK-04"]},
      {n: 28, kind: "typical", plate: "/dlf/t03-floor_plan-p15.jpg", configs: ["T03-3BHK-01", "T03-3BHK-02", "T03-3BHK-03", "T03-3BHK-04"]},
      {n: 29, kind: "refuge-variant", plate: "/dlf/t03-floor_plan-p16.jpg", configs: ["T03-3BHK-01", "T03-3BHK-02", "T03-3BHK-03"]},
      {n: 30, kind: "typical", plate: "/dlf/t03-floor_plan-p15.jpg", configs: ["T03-3BHK-01", "T03-3BHK-02", "T03-3BHK-03", "T03-3BHK-04"]},
      {n: 31, kind: "typical", plate: "/dlf/t03-floor_plan-p15.jpg", configs: ["T03-3BHK-01", "T03-3BHK-02", "T03-3BHK-03", "T03-3BHK-04"]},
      {n: 32, kind: "typical", plate: "/dlf/t03-floor_plan-p15.jpg", configs: ["T03-3BHK-01", "T03-3BHK-02", "T03-3BHK-03", "T03-3BHK-04"]},
      {n: 33, kind: "typical", plate: "/dlf/t03-floor_plan-p15.jpg", configs: ["T03-3BHK-01", "T03-3BHK-02", "T03-3BHK-03", "T03-3BHK-04"]},
      {n: 34, kind: "typical", plate: "/dlf/t03-floor_plan-p15.jpg", configs: ["T03-3BHK-01", "T03-3BHK-02", "T03-3BHK-03", "T03-3BHK-04"]},
      {n: 35, kind: "typical", plate: "/dlf/t03-floor_plan-p15.jpg", configs: ["T03-3BHK-01", "T03-3BHK-02", "T03-3BHK-03", "T03-3BHK-04"]},
      {n: 36, kind: "typical", plate: "/dlf/t03-floor_plan-p17.jpg", configs: ["T03-3BHK-01", "T03-3BHK-02", "T03-4BHK-03"]},
      {n: 37, kind: "typical", plate: "/dlf/t03-floor_plan-p15.jpg", configs: ["T03-3BHK-01", "T03-3BHK-02", "T03-3BHK-03", "T03-3BHK-04"]},
      {n: 38, kind: "typical", plate: "/dlf/t03-floor_plan-p15.jpg", configs: ["T03-3BHK-01", "T03-3BHK-02", "T03-3BHK-03", "T03-3BHK-04"]},
      {n: 39, kind: "duplex", plate: "/dlf/t03-floor_plan-p18.jpg", configs: ["T03-3BHK-03", "T03-3BHK-04", "T03-4BHK-DUPLEX-01", "T03-4BHK-DUPLEX-02"]},
      {n: 40, kind: "duplex", plate: "/dlf/t03-floor_plan-p19.jpg", configs: ["T03-4BHK-DUPLEX-01", "T03-4BHK-DUPLEX-02"]}
    ],
  },
  {
    id: "T04",
    name: "Tower-04",
    floorCount: 40,
    configs: [
      {id: "T04-3BHK-01", unit: "01", label: "3 BHK", carpetSqft: 1255.29, balconySqft: 103.99, totalSqft: 1359.28, floors: "3–12, 14–38", planImage: "/dlf/t04-3bhk-01-floor_plan-p30.jpg"},
      {id: "T04-3BHK-02", unit: "02", label: "3 BHK", carpetSqft: 1084.2, balconySqft: 78.33, totalSqft: 1162.53, floors: "3–6, 8–12, 14, 16–21, 23–28, 30–35, 37–39", planImage: "/dlf/t04-3bhk-01-floor_plan-p30.jpg"},
      {id: "T04-3BHK-03", unit: "03", label: "3 BHK", carpetSqft: 1048.07, balconySqft: 78.33, totalSqft: 1126.4, floors: "3–6, 8–12, 14, 16–21, 23–28, 30–35, 37–39", planImage: "/dlf/t04-3bhk-03-floor_plan-p31.jpg"},
      {id: "T04-4BHK-03", unit: "03", label: "4 BHK", carpetSqft: 1246.2, balconySqft: 78.33, totalSqft: 1324.53, floors: "7, 15, 22, 29", planImage: "/dlf/t04-4bhk-03-floor_plan-p32.jpg"},
      {id: "T04-4BHK-03-FL36", unit: "03", label: "4 BHK", carpetSqft: 1510.37, balconySqft: 138.24, totalSqft: 1648.61, floors: "36", planImage: "/dlf/t04-4bhk-03-fl36-floor_plan-p33.jpg"},
      {id: "T04-4BHK-DUPLEX-01", unit: "01", label: "4 BHK Duplex", carpetSqft: 2078.79, balconySqft: 162.06, totalSqft: 2240.85, floors: "39 (lower) + 40 (upper)", planImage: "/dlf/t04-4bhk-duplex-01-floor_plan-p34.jpg"}
    ],
    floors: [
      {n: 3, kind: "typical", plate: "/dlf/t04-floor_plan-p25.jpg", configs: ["T04-3BHK-01", "T04-3BHK-02", "T04-3BHK-03"]},
      {n: 4, kind: "typical", plate: "/dlf/t04-floor_plan-p25.jpg", configs: ["T04-3BHK-01", "T04-3BHK-02", "T04-3BHK-03"]},
      {n: 5, kind: "typical", plate: "/dlf/t04-floor_plan-p25.jpg", configs: ["T04-3BHK-01", "T04-3BHK-02", "T04-3BHK-03"]},
      {n: 6, kind: "typical", plate: "/dlf/t04-floor_plan-p25.jpg", configs: ["T04-3BHK-01", "T04-3BHK-02", "T04-3BHK-03"]},
      {n: 7, kind: "refuge-variant", plate: "/dlf/t04-floor_plan-p26.jpg", configs: ["T04-3BHK-01", "T04-4BHK-03"]},
      {n: 8, kind: "typical", plate: "/dlf/t04-floor_plan-p25.jpg", configs: ["T04-3BHK-01", "T04-3BHK-02", "T04-3BHK-03"]},
      {n: 9, kind: "typical", plate: "/dlf/t04-floor_plan-p25.jpg", configs: ["T04-3BHK-01", "T04-3BHK-02", "T04-3BHK-03"]},
      {n: 10, kind: "typical", plate: "/dlf/t04-floor_plan-p25.jpg", configs: ["T04-3BHK-01", "T04-3BHK-02", "T04-3BHK-03"]},
      {n: 11, kind: "typical", plate: "/dlf/t04-floor_plan-p25.jpg", configs: ["T04-3BHK-01", "T04-3BHK-02", "T04-3BHK-03"]},
      {n: 12, kind: "typical", plate: "/dlf/t04-floor_plan-p25.jpg", configs: ["T04-3BHK-01", "T04-3BHK-02", "T04-3BHK-03"]},
      {n: 13, kind: "refuge", plate: null, configs: []},
      {n: 14, kind: "typical", plate: "/dlf/t04-floor_plan-p25.jpg", configs: ["T04-3BHK-01", "T04-3BHK-02", "T04-3BHK-03"]},
      {n: 15, kind: "refuge-variant", plate: "/dlf/t04-floor_plan-p26.jpg", configs: ["T04-3BHK-01", "T04-4BHK-03"]},
      {n: 16, kind: "typical", plate: "/dlf/t04-floor_plan-p25.jpg", configs: ["T04-3BHK-01", "T04-3BHK-02", "T04-3BHK-03"]},
      {n: 17, kind: "typical", plate: "/dlf/t04-floor_plan-p25.jpg", configs: ["T04-3BHK-01", "T04-3BHK-02", "T04-3BHK-03"]},
      {n: 18, kind: "typical", plate: "/dlf/t04-floor_plan-p25.jpg", configs: ["T04-3BHK-01", "T04-3BHK-02", "T04-3BHK-03"]},
      {n: 19, kind: "typical", plate: "/dlf/t04-floor_plan-p25.jpg", configs: ["T04-3BHK-01", "T04-3BHK-02", "T04-3BHK-03"]},
      {n: 20, kind: "typical", plate: "/dlf/t04-floor_plan-p25.jpg", configs: ["T04-3BHK-01", "T04-3BHK-02", "T04-3BHK-03"]},
      {n: 21, kind: "typical", plate: "/dlf/t04-floor_plan-p25.jpg", configs: ["T04-3BHK-01", "T04-3BHK-02", "T04-3BHK-03"]},
      {n: 22, kind: "refuge-variant", plate: "/dlf/t04-floor_plan-p26.jpg", configs: ["T04-3BHK-01", "T04-4BHK-03"]},
      {n: 23, kind: "typical", plate: "/dlf/t04-floor_plan-p25.jpg", configs: ["T04-3BHK-01", "T04-3BHK-02", "T04-3BHK-03"]},
      {n: 24, kind: "typical", plate: "/dlf/t04-floor_plan-p25.jpg", configs: ["T04-3BHK-01", "T04-3BHK-02", "T04-3BHK-03"]},
      {n: 25, kind: "typical", plate: "/dlf/t04-floor_plan-p25.jpg", configs: ["T04-3BHK-01", "T04-3BHK-02", "T04-3BHK-03"]},
      {n: 26, kind: "typical", plate: "/dlf/t04-floor_plan-p25.jpg", configs: ["T04-3BHK-01", "T04-3BHK-02", "T04-3BHK-03"]},
      {n: 27, kind: "typical", plate: "/dlf/t04-floor_plan-p25.jpg", configs: ["T04-3BHK-01", "T04-3BHK-02", "T04-3BHK-03"]},
      {n: 28, kind: "typical", plate: "/dlf/t04-floor_plan-p25.jpg", configs: ["T04-3BHK-01", "T04-3BHK-02", "T04-3BHK-03"]},
      {n: 29, kind: "refuge-variant", plate: "/dlf/t04-floor_plan-p26.jpg", configs: ["T04-3BHK-01", "T04-4BHK-03"]},
      {n: 30, kind: "typical", plate: "/dlf/t04-floor_plan-p25.jpg", configs: ["T04-3BHK-01", "T04-3BHK-02", "T04-3BHK-03"]},
      {n: 31, kind: "typical", plate: "/dlf/t04-floor_plan-p25.jpg", configs: ["T04-3BHK-01", "T04-3BHK-02", "T04-3BHK-03"]},
      {n: 32, kind: "typical", plate: "/dlf/t04-floor_plan-p25.jpg", configs: ["T04-3BHK-01", "T04-3BHK-02", "T04-3BHK-03"]},
      {n: 33, kind: "typical", plate: "/dlf/t04-floor_plan-p25.jpg", configs: ["T04-3BHK-01", "T04-3BHK-02", "T04-3BHK-03"]},
      {n: 34, kind: "typical", plate: "/dlf/t04-floor_plan-p25.jpg", configs: ["T04-3BHK-01", "T04-3BHK-02", "T04-3BHK-03"]},
      {n: 35, kind: "typical", plate: "/dlf/t04-floor_plan-p25.jpg", configs: ["T04-3BHK-01", "T04-3BHK-02", "T04-3BHK-03"]},
      {n: 36, kind: "typical", plate: "/dlf/t04-floor_plan-p27.jpg", configs: ["T04-3BHK-01", "T04-4BHK-03-FL36"]},
      {n: 37, kind: "typical", plate: "/dlf/t04-floor_plan-p25.jpg", configs: ["T04-3BHK-01", "T04-3BHK-02", "T04-3BHK-03"]},
      {n: 38, kind: "typical", plate: "/dlf/t04-floor_plan-p25.jpg", configs: ["T04-3BHK-01", "T04-3BHK-02", "T04-3BHK-03"]},
      {n: 39, kind: "duplex", plate: "/dlf/t04-floor_plan-p28.jpg", configs: ["T04-3BHK-02", "T04-3BHK-03", "T04-4BHK-DUPLEX-01"]},
      {n: 40, kind: "duplex", plate: "/dlf/t04-floor_plan-p29.jpg", configs: ["T04-4BHK-DUPLEX-01"]}
    ],
  },
  {
    id: "T05",
    name: "Tower-05",
    floorCount: 40,
    configs: [
      {id: "T05-3BHK-01", unit: "01", label: "3 BHK", carpetSqft: 1368.37, balconySqft: 99.45, totalSqft: 1467.82, floors: "3–6, 8–12, 14, 16–21, 23–28, 30–35, 37–38", planImage: "/dlf/t05-3bhk-01-floor_plan-p40.jpg"},
      {id: "T05-3BHK-02", unit: "02", label: "3 BHK", carpetSqft: 1362.13, balconySqft: 147.07, totalSqft: 1509.2, floors: "3–12, 14–38", planImage: "/dlf/t05-3bhk-02-floor_plan-p41.jpg"},
      {id: "T05-3BHK-03", unit: "03", label: "3 BHK", carpetSqft: 1363.27, balconySqft: 147.54, totalSqft: 1510.81, floors: "3–12, 14–38", planImage: "/dlf/t05-3bhk-02-floor_plan-p41.jpg"},
      {id: "T05-STUDIO-01-REFUGE", unit: "01", label: "Studio", carpetSqft: 245.25, balconySqft: 0, totalSqft: 245.25, floors: "7, 15, 22, 29", planImage: "/dlf/t05-3bhk-03-floor_plan-p42.jpg"},
      {id: "T05-STUDIO-01-FL36", unit: "01", label: "Studio", carpetSqft: 477.78, balconySqft: 71.7, totalSqft: 549.48, floors: "36", planImage: "/dlf/t05-studio-01-fl36-floor_plan-p43.jpg"},
      {id: "T05-4BHK-DUPLEX-02", unit: "02", label: "4 BHK Duplex", carpetSqft: 2277.12, balconySqft: 255.68, totalSqft: 2532.8, floors: "39 (lower) + 40 (upper)", planImage: "/dlf/t05-4bhk-duplex-02-floor_plan-p44.jpg"},
      {id: "T05-4BHK-DUPLEX-03", unit: "03", label: "4 BHK Duplex", carpetSqft: 2278.27, balconySqft: 256.15, totalSqft: 2534.42, floors: "39 (lower) + 40 (upper)", planImage: "/dlf/t05-4bhk-duplex-02-floor_plan-p44.jpg"}
    ],
    floors: [
      {n: 3, kind: "typical", plate: "/dlf/t05-floor_plan-p35.jpg", configs: ["T05-3BHK-01", "T05-3BHK-02", "T05-3BHK-03"]},
      {n: 4, kind: "typical", plate: "/dlf/t05-floor_plan-p35.jpg", configs: ["T05-3BHK-01", "T05-3BHK-02", "T05-3BHK-03"]},
      {n: 5, kind: "typical", plate: "/dlf/t05-floor_plan-p35.jpg", configs: ["T05-3BHK-01", "T05-3BHK-02", "T05-3BHK-03"]},
      {n: 6, kind: "typical", plate: "/dlf/t05-floor_plan-p35.jpg", configs: ["T05-3BHK-01", "T05-3BHK-02", "T05-3BHK-03"]},
      {n: 7, kind: "refuge-variant", plate: "/dlf/t05-floor_plan-p36.jpg", configs: ["T05-3BHK-02", "T05-3BHK-03", "T05-STUDIO-01-REFUGE"]},
      {n: 8, kind: "typical", plate: "/dlf/t05-floor_plan-p35.jpg", configs: ["T05-3BHK-01", "T05-3BHK-02", "T05-3BHK-03"]},
      {n: 9, kind: "typical", plate: "/dlf/t05-floor_plan-p35.jpg", configs: ["T05-3BHK-01", "T05-3BHK-02", "T05-3BHK-03"]},
      {n: 10, kind: "typical", plate: "/dlf/t05-floor_plan-p35.jpg", configs: ["T05-3BHK-01", "T05-3BHK-02", "T05-3BHK-03"]},
      {n: 11, kind: "typical", plate: "/dlf/t05-floor_plan-p35.jpg", configs: ["T05-3BHK-01", "T05-3BHK-02", "T05-3BHK-03"]},
      {n: 12, kind: "typical", plate: "/dlf/t05-floor_plan-p35.jpg", configs: ["T05-3BHK-01", "T05-3BHK-02", "T05-3BHK-03"]},
      {n: 13, kind: "refuge", plate: null, configs: []},
      {n: 14, kind: "typical", plate: "/dlf/t05-floor_plan-p35.jpg", configs: ["T05-3BHK-01", "T05-3BHK-02", "T05-3BHK-03"]},
      {n: 15, kind: "refuge-variant", plate: "/dlf/t05-floor_plan-p36.jpg", configs: ["T05-3BHK-02", "T05-3BHK-03", "T05-STUDIO-01-REFUGE"]},
      {n: 16, kind: "typical", plate: "/dlf/t05-floor_plan-p35.jpg", configs: ["T05-3BHK-01", "T05-3BHK-02", "T05-3BHK-03"]},
      {n: 17, kind: "typical", plate: "/dlf/t05-floor_plan-p35.jpg", configs: ["T05-3BHK-01", "T05-3BHK-02", "T05-3BHK-03"]},
      {n: 18, kind: "typical", plate: "/dlf/t05-floor_plan-p35.jpg", configs: ["T05-3BHK-01", "T05-3BHK-02", "T05-3BHK-03"]},
      {n: 19, kind: "typical", plate: "/dlf/t05-floor_plan-p35.jpg", configs: ["T05-3BHK-01", "T05-3BHK-02", "T05-3BHK-03"]},
      {n: 20, kind: "typical", plate: "/dlf/t05-floor_plan-p35.jpg", configs: ["T05-3BHK-01", "T05-3BHK-02", "T05-3BHK-03"]},
      {n: 21, kind: "typical", plate: "/dlf/t05-floor_plan-p35.jpg", configs: ["T05-3BHK-01", "T05-3BHK-02", "T05-3BHK-03"]},
      {n: 22, kind: "refuge-variant", plate: "/dlf/t05-floor_plan-p36.jpg", configs: ["T05-3BHK-02", "T05-3BHK-03", "T05-STUDIO-01-REFUGE"]},
      {n: 23, kind: "typical", plate: "/dlf/t05-floor_plan-p35.jpg", configs: ["T05-3BHK-01", "T05-3BHK-02", "T05-3BHK-03"]},
      {n: 24, kind: "typical", plate: "/dlf/t05-floor_plan-p35.jpg", configs: ["T05-3BHK-01", "T05-3BHK-02", "T05-3BHK-03"]},
      {n: 25, kind: "typical", plate: "/dlf/t05-floor_plan-p35.jpg", configs: ["T05-3BHK-01", "T05-3BHK-02", "T05-3BHK-03"]},
      {n: 26, kind: "typical", plate: "/dlf/t05-floor_plan-p35.jpg", configs: ["T05-3BHK-01", "T05-3BHK-02", "T05-3BHK-03"]},
      {n: 27, kind: "typical", plate: "/dlf/t05-floor_plan-p35.jpg", configs: ["T05-3BHK-01", "T05-3BHK-02", "T05-3BHK-03"]},
      {n: 28, kind: "typical", plate: "/dlf/t05-floor_plan-p35.jpg", configs: ["T05-3BHK-01", "T05-3BHK-02", "T05-3BHK-03"]},
      {n: 29, kind: "refuge-variant", plate: "/dlf/t05-floor_plan-p36.jpg", configs: ["T05-3BHK-02", "T05-3BHK-03", "T05-STUDIO-01-REFUGE"]},
      {n: 30, kind: "typical", plate: "/dlf/t05-floor_plan-p35.jpg", configs: ["T05-3BHK-01", "T05-3BHK-02", "T05-3BHK-03"]},
      {n: 31, kind: "typical", plate: "/dlf/t05-floor_plan-p35.jpg", configs: ["T05-3BHK-01", "T05-3BHK-02", "T05-3BHK-03"]},
      {n: 32, kind: "typical", plate: "/dlf/t05-floor_plan-p35.jpg", configs: ["T05-3BHK-01", "T05-3BHK-02", "T05-3BHK-03"]},
      {n: 33, kind: "typical", plate: "/dlf/t05-floor_plan-p35.jpg", configs: ["T05-3BHK-01", "T05-3BHK-02", "T05-3BHK-03"]},
      {n: 34, kind: "typical", plate: "/dlf/t05-floor_plan-p35.jpg", configs: ["T05-3BHK-01", "T05-3BHK-02", "T05-3BHK-03"]},
      {n: 35, kind: "typical", plate: "/dlf/t05-floor_plan-p35.jpg", configs: ["T05-3BHK-01", "T05-3BHK-02", "T05-3BHK-03"]},
      {n: 36, kind: "typical", plate: "/dlf/t05-floor_plan-p37.jpg", configs: ["T05-3BHK-02", "T05-3BHK-03", "T05-STUDIO-01-FL36"]},
      {n: 37, kind: "typical", plate: "/dlf/t05-floor_plan-p35.jpg", configs: ["T05-3BHK-01", "T05-3BHK-02", "T05-3BHK-03"]},
      {n: 38, kind: "typical", plate: "/dlf/t05-floor_plan-p35.jpg", configs: ["T05-3BHK-01", "T05-3BHK-02", "T05-3BHK-03"]},
      {n: 39, kind: "duplex", plate: "/dlf/t05-floor_plan-p38.jpg", configs: ["T05-4BHK-DUPLEX-02", "T05-4BHK-DUPLEX-03"]},
      {n: 40, kind: "duplex", plate: "/dlf/t05-floor_plan-p39.jpg", configs: ["T05-4BHK-DUPLEX-02", "T05-4BHK-DUPLEX-03"]}
    ],
  },
];
