/**
 * Neighborhood POIs per focus building — GENERATED by scripts/export_neighborhoods.py
 * from OSM Overpass (radius 1500m). Data © OpenStreetMap contributors.
 * Do not hand-edit; rerun the script. Curate by editing MAX_PER_CAT/CATS there.
 */

export interface Poi {
  name: string;
  lat: number;
  lng: number;
}

export const POI_CATEGORIES: { key: string; label: string; color: string }[] = [
  { key: "transit", label: "Transit", color: "#1f3d4d" },
  { key: "schools", label: "Schools", color: "#3e82b0" },
  { key: "health", label: "Healthcare", color: "#c2493d" },
  { key: "food", label: "Food & Cafés", color: "#b6862c" },
  { key: "retail", label: "Retail", color: "#2c5364" },
  { key: "parks", label: "Parks", color: "#4c7a5a" },
];

export const neighborhoods: Record<string, Record<string, Poi[]>> = {
  "ekta-tripolis": {
    "transit": [
      {
        "name": "Goregaon",
        "lat": 19.16487,
        "lng": 72.84955
      },
      {
        "name": "Ram Mandir",
        "lat": 19.15102,
        "lng": 72.85015
      },
      {
        "name": "Oshiwara",
        "lat": 19.14604,
        "lng": 72.83395
      },
      {
        "name": "Goregaon (West)",
        "lat": 19.15302,
        "lng": 72.83567
      },
      {
        "name": "Bangur Nagar",
        "lat": 19.16247,
        "lng": 72.83487
      }
    ],
    "schools": [
      {
        "name": "St. Thomas School",
        "lat": 19.16703,
        "lng": 72.84983
      },
      {
        "name": "IB Patel School",
        "lat": 19.15784,
        "lng": 72.84766
      },
      {
        "name": "Rims Internation School",
        "lat": 19.15151,
        "lng": 72.82979
      },
      {
        "name": "HVPS College",
        "lat": 19.15075,
        "lng": 72.83065
      },
      {
        "name": "Goenka School",
        "lat": 19.15074,
        "lng": 72.83076
      },
      {
        "name": "Marble the Arc",
        "lat": 19.15068,
        "lng": 72.83092
      }
    ],
    "health": [
      {
        "name": "Siddarth Municipal Hospital",
        "lat": 19.15972,
        "lng": 72.83992
      },
      {
        "name": "Dr Baliga Nursing Home",
        "lat": 19.16421,
        "lng": 72.84569
      },
      {
        "name": "Kapadia Multi Speciality Hospital",
        "lat": 19.16311,
        "lng": 72.84348
      },
      {
        "name": "Dr. Bamis Fracture and Hand Clinic - Goregaon",
        "lat": 19.15689,
        "lng": 72.84563
      },
      {
        "name": "Pooja Hospital, Mumbai",
        "lat": 19.1555,
        "lng": 72.8455
      },
      {
        "name": "Navjeevan Urology and Stone Care Centre",
        "lat": 19.16601,
        "lng": 72.85076
      }
    ],
    "food": [
      {
        "name": "Sai Veg World",
        "lat": 19.16481,
        "lng": 72.85027
      },
      {
        "name": "Ratna",
        "lat": 19.16335,
        "lng": 72.84612
      },
      {
        "name": "Shreeji's",
        "lat": 19.14878,
        "lng": 72.83162
      },
      {
        "name": "Lucky Biryani",
        "lat": 19.15097,
        "lng": 72.83558
      },
      {
        "name": "Cafe Coffee Day",
        "lat": 19.15146,
        "lng": 72.83192
      },
      {
        "name": "Sweet Corner",
        "lat": 19.14381,
        "lng": 72.84261
      }
    ],
    "retail": [
      {
        "name": "City Centre Mall",
        "lat": 19.16234,
        "lng": 72.84576
      },
      {
        "name": "misha supermarket",
        "lat": 19.15928,
        "lng": 72.84126
      },
      {
        "name": "Harmony Mall",
        "lat": 19.1576,
        "lng": 72.83468
      },
      {
        "name": "National",
        "lat": 19.14535,
        "lng": 72.84676
      },
      {
        "name": "Mega Mall",
        "lat": 19.15183,
        "lng": 72.83433
      }
    ],
    "parks": [
      {
        "name": "B.R. Ambedkar park",
        "lat": 19.16518,
        "lng": 72.84718
      },
      {
        "name": "Guru Nanak Park",
        "lat": 19.16055,
        "lng": 72.83879
      },
      {
        "name": "Kamalakarpant Walawalkar Udyan",
        "lat": 19.15296,
        "lng": 72.82916
      },
      {
        "name": "Oshiwara Mahada Garden",
        "lat": 19.14974,
        "lng": 72.83076
      },
      {
        "name": "Dr. B. R. Ambedkar Maidan",
        "lat": 19.15683,
        "lng": 72.83874
      },
      {
        "name": "Trikoni Maidan",
        "lat": 19.15463,
        "lng": 72.83859
      }
    ]
  },
  "imperial-heights": {
    "transit": [
      {
        "name": "Ram Mandir",
        "lat": 19.15102,
        "lng": 72.85015
      },
      {
        "name": "Oshiwara",
        "lat": 19.14604,
        "lng": 72.83395
      },
      {
        "name": "Goregaon (West)",
        "lat": 19.15302,
        "lng": 72.83567
      },
      {
        "name": "Bangur Nagar",
        "lat": 19.16247,
        "lng": 72.83487
      }
    ],
    "schools": [
      {
        "name": "IB Patel School",
        "lat": 19.15784,
        "lng": 72.84766
      },
      {
        "name": "Rims Internation School",
        "lat": 19.15151,
        "lng": 72.82979
      },
      {
        "name": "HVPS College",
        "lat": 19.15075,
        "lng": 72.83065
      },
      {
        "name": "Goenka School",
        "lat": 19.15074,
        "lng": 72.83076
      },
      {
        "name": "Marble the Arc",
        "lat": 19.15068,
        "lng": 72.83092
      },
      {
        "name": "Vibgyor",
        "lat": 19.15953,
        "lng": 72.83614
      }
    ],
    "health": [
      {
        "name": "Siddarth Municipal Hospital",
        "lat": 19.15972,
        "lng": 72.83992
      },
      {
        "name": "Dr Baliga Nursing Home",
        "lat": 19.16421,
        "lng": 72.84569
      },
      {
        "name": "Kapadia Multi Speciality Hospital",
        "lat": 19.16311,
        "lng": 72.84348
      },
      {
        "name": "Dr. Bamis Fracture and Hand Clinic - Goregaon",
        "lat": 19.15689,
        "lng": 72.84563
      },
      {
        "name": "Pooja Hospital, Mumbai",
        "lat": 19.1555,
        "lng": 72.8455
      },
      {
        "name": "Vital Care Centre",
        "lat": 19.14689,
        "lng": 72.83115
      }
    ],
    "food": [
      {
        "name": "Ratna",
        "lat": 19.16335,
        "lng": 72.84612
      },
      {
        "name": "Shreeji's",
        "lat": 19.14878,
        "lng": 72.83162
      },
      {
        "name": "Third Wave Coffee Roasters",
        "lat": 19.14666,
        "lng": 72.82875
      },
      {
        "name": "Starbucks",
        "lat": 19.14657,
        "lng": 72.82916
      },
      {
        "name": "Mainland China",
        "lat": 19.14148,
        "lng": 72.8323
      },
      {
        "name": "Lucky Biryani",
        "lat": 19.15097,
        "lng": 72.83558
      }
    ],
    "retail": [
      {
        "name": "Crystal Plaza",
        "lat": 19.14085,
        "lng": 72.83246
      },
      {
        "name": "City Centre Mall",
        "lat": 19.16234,
        "lng": 72.84576
      },
      {
        "name": "Nature's Basket",
        "lat": 19.14543,
        "lng": 72.82925
      },
      {
        "name": "Aksar grocery shop",
        "lat": 19.14033,
        "lng": 72.83754
      },
      {
        "name": "misha supermarket",
        "lat": 19.15928,
        "lng": 72.84126
      },
      {
        "name": "Harmony Mall",
        "lat": 19.1576,
        "lng": 72.83468
      }
    ],
    "parks": [
      {
        "name": "Guru Nanak Park",
        "lat": 19.16055,
        "lng": 72.83879
      },
      {
        "name": "Kamalakarpant Walawalkar Udyan",
        "lat": 19.15296,
        "lng": 72.82916
      },
      {
        "name": "The Grand Hamvi Garden",
        "lat": 19.13923,
        "lng": 72.83661
      },
      {
        "name": "Oshiwara Mahada Garden",
        "lat": 19.14974,
        "lng": 72.83076
      },
      {
        "name": "ramraj park",
        "lat": 19.14204,
        "lng": 72.84791
      },
      {
        "name": "Dr. B. R. Ambedkar Maidan",
        "lat": 19.15683,
        "lng": 72.83874
      }
    ]
  },
  "kalpataru-radiance": {
    "transit": [
      {
        "name": "Goregaon",
        "lat": 19.16487,
        "lng": 72.84955
      },
      {
        "name": "Goregaon (West)",
        "lat": 19.15302,
        "lng": 72.83567
      },
      {
        "name": "Lower Malad",
        "lat": 19.1731,
        "lng": 72.83648
      },
      {
        "name": "Bangur Nagar",
        "lat": 19.16247,
        "lng": 72.83487
      }
    ],
    "schools": [
      {
        "name": "IB Patel School",
        "lat": 19.15784,
        "lng": 72.84766
      },
      {
        "name": "Rims Internation School",
        "lat": 19.15151,
        "lng": 72.82979
      },
      {
        "name": "HVPS College",
        "lat": 19.15075,
        "lng": 72.83065
      },
      {
        "name": "Goenka School",
        "lat": 19.15074,
        "lng": 72.83076
      },
      {
        "name": "Marble the Arc",
        "lat": 19.15068,
        "lng": 72.83092
      },
      {
        "name": "Vibgyor",
        "lat": 19.15953,
        "lng": 72.83614
      }
    ],
    "health": [
      {
        "name": "Siddarth Municipal Hospital",
        "lat": 19.15972,
        "lng": 72.83992
      },
      {
        "name": "Dr Baliga Nursing Home",
        "lat": 19.16421,
        "lng": 72.84569
      },
      {
        "name": "Kapadia Multi Speciality Hospital",
        "lat": 19.16311,
        "lng": 72.84348
      },
      {
        "name": "Dr. Bamis Fracture and Hand Clinic - Goregaon",
        "lat": 19.15689,
        "lng": 72.84563
      },
      {
        "name": "Pooja Hospital, Mumbai",
        "lat": 19.1555,
        "lng": 72.8455
      },
      {
        "name": "Vardan Nursing Home Pvt.Ltd.",
        "lat": 19.16543,
        "lng": 72.83883
      }
    ],
    "food": [
      {
        "name": "Sai Veg World",
        "lat": 19.16481,
        "lng": 72.85027
      },
      {
        "name": "Ratna",
        "lat": 19.16335,
        "lng": 72.84612
      },
      {
        "name": "Shreeji's",
        "lat": 19.14878,
        "lng": 72.83162
      },
      {
        "name": "Lucky Biryani",
        "lat": 19.15097,
        "lng": 72.83558
      },
      {
        "name": "Cafe Coffee Day",
        "lat": 19.15146,
        "lng": 72.83192
      },
      {
        "name": "Loco Chino",
        "lat": 19.1509,
        "lng": 72.83141
      }
    ],
    "retail": [
      {
        "name": "City Centre Mall",
        "lat": 19.16234,
        "lng": 72.84576
      },
      {
        "name": "misha supermarket",
        "lat": 19.15928,
        "lng": 72.84126
      },
      {
        "name": "Harmony Mall",
        "lat": 19.1576,
        "lng": 72.83468
      },
      {
        "name": "InOrbit Mall",
        "lat": 19.17294,
        "lng": 72.83545
      },
      {
        "name": "Mega Mall",
        "lat": 19.15183,
        "lng": 72.83433
      }
    ],
    "parks": [
      {
        "name": "B.R. Ambedkar park",
        "lat": 19.16518,
        "lng": 72.84718
      },
      {
        "name": "Guru Nanak Park",
        "lat": 19.16055,
        "lng": 72.83879
      },
      {
        "name": "Kamalakarpant Walawalkar Udyan",
        "lat": 19.15296,
        "lng": 72.82916
      },
      {
        "name": "BMC Forest Theme Garden",
        "lat": 19.17343,
        "lng": 72.83319
      },
      {
        "name": "Oshiwara Mahada Garden",
        "lat": 19.14974,
        "lng": 72.83076
      },
      {
        "name": "Dr. B. R. Ambedkar Maidan",
        "lat": 19.15683,
        "lng": 72.83874
      }
    ]
  },
  "dlf-westpark": {
    "transit": [
      {
        "name": "DN Nagar",
        "lat": 19.12783,
        "lng": 72.83086
      },
      {
        "name": "Versova",
        "lat": 19.1305,
        "lng": 72.82066
      },
      {
        "name": "Andheri (West)",
        "lat": 19.12913,
        "lng": 72.83143
      },
      {
        "name": "Lower Oshiwara",
        "lat": 19.1407,
        "lng": 72.83171
      },
      {
        "name": "Gate No.3",
        "lat": 19.12828,
        "lng": 72.83093
      },
      {
        "name": "Gate No.2",
        "lat": 19.12843,
        "lng": 72.83018
      }
    ],
    "schools": [
      {
        "name": "Holy Cross Convent",
        "lat": 19.13189,
        "lng": 72.8142
      },
      {
        "name": "Cosmopolitan Education Society",
        "lat": 19.12465,
        "lng": 72.82998
      },
      {
        "name": "Kishore Namit Kapoor Acting Institute",
        "lat": 19.13987,
        "lng": 72.81946
      },
      {
        "name": "A.H. Wadia High School",
        "lat": 19.12665,
        "lng": 72.83449
      },
      {
        "name": "Gyan Kendra Higher Secondary School",
        "lat": 19.13235,
        "lng": 72.82486
      },
      {
        "name": "Jankidevi Public School",
        "lat": 19.13931,
        "lng": 72.81957
      }
    ],
    "health": [
      {
        "name": "Dr Manveen Gill",
        "lat": 19.13248,
        "lng": 72.82749
      },
      {
        "name": "Dr CV Hemlata",
        "lat": 19.13015,
        "lng": 72.82101
      },
      {
        "name": "Dr M S Jayaprakash",
        "lat": 19.13016,
        "lng": 72.8192
      },
      {
        "name": "Dr Nischint Jayaprakash",
        "lat": 19.13015,
        "lng": 72.81913
      },
      {
        "name": "Dr Dharampal Singh",
        "lat": 19.13665,
        "lng": 72.82814
      },
      {
        "name": "Vital Imaging Centre",
        "lat": 19.13962,
        "lng": 72.83119
      }
    ],
    "food": [
      {
        "name": "Red Box",
        "lat": 19.13997,
        "lng": 72.83137
      },
      {
        "name": "Caravan Serai",
        "lat": 19.13986,
        "lng": 72.83139
      },
      {
        "name": "Infinity Mall Food Court",
        "lat": 19.14125,
        "lng": 72.83109
      },
      {
        "name": "Delicacy Of China",
        "lat": 19.14214,
        "lng": 72.8291
      },
      {
        "name": "Costa",
        "lat": 19.142,
        "lng": 72.82907
      },
      {
        "name": "Cafe Coffee Day",
        "lat": 19.14137,
        "lng": 72.83123
      }
    ],
    "retail": [
      {
        "name": "Crystal Plaza",
        "lat": 19.14085,
        "lng": 72.83246
      },
      {
        "name": "MG365",
        "lat": 19.13478,
        "lng": 72.82509
      },
      {
        "name": "Health & More",
        "lat": 19.13304,
        "lng": 72.82555
      },
      {
        "name": "Heath Guard Chemist and Supermarket",
        "lat": 19.12777,
        "lng": 72.83176
      },
      {
        "name": "Apna Bazar",
        "lat": 19.12797,
        "lng": 72.83241
      },
      {
        "name": "Tirumala Shopping Center",
        "lat": 19.12909,
        "lng": 72.82798
      }
    ],
    "parks": [
      {
        "name": "svp garden",
        "lat": 19.13404,
        "lng": 72.82612
      },
      {
        "name": "Bharatratna Doctor Babasaheb Ambedkar Kridangan",
        "lat": 19.13697,
        "lng": 72.82125
      },
      {
        "name": "Brihan Mumbai Municipal Corporation Park",
        "lat": 19.13729,
        "lng": 72.81415
      },
      {
        "name": "Swatantra Senani Janardan Rama Patil Park",
        "lat": 19.13771,
        "lng": 72.81583
      },
      {
        "name": "Nana Nani Park",
        "lat": 19.12768,
        "lng": 72.81839
      },
      {
        "name": "Hemu Kalani Manoranjan Maidan",
        "lat": 19.13953,
        "lng": 72.82904
      }
    ]
  }
};
