#!/usr/bin/env python3
"""Export neighborhood POIs around each focus building → web/src/lib/neighborhoods.ts

Queries OSM Overpass (free) for named POIs within RADIUS_M of each building in
web/src/lib/site.ts mapBuildings (coords duplicated here to stay stdlib-only).
Categories mirror the Tavalo 'Explore the Neighborhood' pattern.

Usage: python3 scripts/export_neighborhoods.py
Rerun whenever coords change. Data source credit: © OpenStreetMap contributors.
"""

import json
import time
import urllib.request
from pathlib import Path

RADIUS_M = 1500
MAX_PER_CAT = 6
OVERPASS = "https://overpass-api.de/api/interpreter"
OUT = Path(__file__).parent.parent / "web" / "src" / "lib" / "neighborhoods.ts"

BUILDINGS = {
    "ekta-tripolis": (19.1544, 72.8421),
    "imperial-heights": (19.15187, 72.84022),
    "kalpataru-radiance": (19.15706, 72.84116),
    "dlf-westpark": (19.1298, 72.8262),
}

# category → (overpass selector list, human label)
CATS = {
    "transit": (['node["railway"="station"]', 'node["station"="subway"]', 'node["railway"="subway_entrance"]'], "Transit"),
    "schools": (['node["amenity"="school"]', 'way["amenity"="school"]', 'node["amenity"="college"]'], "Schools"),
    "health": (['node["amenity"="hospital"]', 'way["amenity"="hospital"]', 'node["amenity"="clinic"]'], "Healthcare"),
    "food": (['node["amenity"="restaurant"]', 'node["amenity"="cafe"]'], "Food & Cafés"),
    "retail": (['way["shop"="mall"]', 'node["shop"="mall"]', 'node["shop"="supermarket"]'], "Retail"),
    "parks": (['way["leisure"="park"]', 'node["leisure"="park"]'], "Parks"),
}


MIRRORS = [OVERPASS, "https://overpass.kumi.systems/api/interpreter"]


def query(lat: float, lng: float, selectors: list[str]) -> list[dict]:
    body = "".join(f'{s}["name"](around:{RADIUS_M},{lat},{lng});' for s in selectors)
    q = f"[out:json][timeout:30];({body});out center tags 40;"
    last: Exception | None = None
    for attempt in range(4):
        url = MIRRORS[attempt % len(MIRRORS)]
        try:
            req = urllib.request.Request(
                url,
                data=("data=" + urllib.parse.quote(q)).encode(),
                headers={"User-Agent": "RDH-neighborhoods/1.0 (hbanthiya@gmail.com)"},
            )
            with urllib.request.urlopen(req, timeout=90) as r:
                return json.load(r)["elements"]
        except Exception as e:  # ponytail: retry-with-mirror covers 504s; anything worse should crash
            last = e
            time.sleep(8 * (attempt + 1))
    raise last  # type: ignore[misc]


def clean(elements: list[dict]) -> list[dict]:
    seen, out = set(), []
    for e in elements:
        name = e.get("tags", {}).get("name")
        if not name or name in seen:
            continue
        lat = e.get("lat") or e.get("center", {}).get("lat")
        lng = e.get("lon") or e.get("center", {}).get("lon")
        if not lat:
            continue
        seen.add(name)
        out.append({"name": name, "lat": round(lat, 5), "lng": round(lng, 5)})
    return out[:MAX_PER_CAT]


import urllib.parse  # noqa: E402

CACHE = Path(__file__).parent.parent / "exports" / "neighborhood_cache.json"
cache: dict = json.loads(CACHE.read_text()) if CACHE.exists() else {}

result: dict[str, dict] = {}
for slug, (lat, lng) in BUILDINGS.items():
    result[slug] = {}
    for cat, (selectors, label) in CATS.items():
        key = f"{slug}:{cat}"
        if key in cache:
            result[slug][cat] = cache[key]
            print(f"{slug} {cat}: {len(cache[key])} (cached)")
            continue
        pois = clean(query(lat, lng, selectors))
        result[slug][cat] = cache[key] = pois
        CACHE.write_text(json.dumps(cache, ensure_ascii=False))
        print(f"{slug} {cat}: {len(pois)}")
        time.sleep(3)  # be polite to Overpass

ts = (
    "/**\n"
    " * Neighborhood POIs per focus building — GENERATED by scripts/export_neighborhoods.py\n"
    f" * from OSM Overpass (radius {RADIUS_M}m). Data © OpenStreetMap contributors.\n"
    " * Do not hand-edit; rerun the script. Curate by editing MAX_PER_CAT/CATS there.\n"
    " */\n\n"
    "export interface Poi {\n  name: string;\n  lat: number;\n  lng: number;\n}\n\n"
    "export const POI_CATEGORIES: { key: string; label: string; color: string }[] = [\n"
    '  { key: "transit", label: "Transit", color: "#1f3d4d" },\n'
    '  { key: "schools", label: "Schools", color: "#3e82b0" },\n'
    '  { key: "health", label: "Healthcare", color: "#c2493d" },\n'
    '  { key: "food", label: "Food & Cafés", color: "#b6862c" },\n'
    '  { key: "retail", label: "Retail", color: "#2c5364" },\n'
    '  { key: "parks", label: "Parks", color: "#4c7a5a" },\n'
    "];\n\n"
    "export const neighborhoods: Record<string, Record<string, Poi[]>> = "
    + json.dumps(result, indent=2, ensure_ascii=False)
    + ";\n"
)
OUT.write_text(ts)
total = sum(len(v) for b in result.values() for v in b.values())
print(f"wrote {OUT} ({total} POIs)")
assert total > 20, "suspiciously few POIs"
