#!/usr/bin/env python3
"""Export DLF Westpark brochure extraction → static TS fixture for the public site.

Reads the authoritative inline data from seed_dlf_brochure_extraction.py (same
source that seeded media_assets) and writes web/src/lib/dlf-plans.ts.
Prod has no DATABASE_URL, so the site must ship this as a build-time fixture.

Usage: python3 scripts/export_dlf_plans.py
"""

import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from seed_dlf_brochure_extraction import EXTRACTION, TOWERS, UNIT_CONFIGS  # noqa: E402

REFUGE_FLOORS = {7, 15, 22, 29}
OUT = Path(__file__).parent.parent / "web" / "src" / "lib" / "dlf-plans.ts"
PUB = Path(__file__).parent.parent / "web" / "public" / "dlf"


def expand_floors(spec: str) -> list[int]:
    """'3–6, 8–12, 14' or '39 (lower) + 40 (upper)' → [3,4,5,6,8,...]"""
    floors: set[int] = set()
    for m in re.finditer(r"(\d+)\s*[–-]\s*(\d+)|\b(\d+)\b", spec):
        if m.group(1):
            floors.update(range(int(m.group(1)), int(m.group(2)) + 1))
        else:
            floors.add(int(m.group(3)))
    return sorted(floors)


def plate_pages(tower: str) -> list[int]:
    """Ordered plate pages on disk for a tower: [typical, refuge, fl36, duplex-lower, duplex-upper]."""
    pages = sorted(
        int(re.search(r"-p(\d+)\.jpg$", f.name).group(1))
        for f in PUB.glob(f"{tower.lower()}-floor_plan-p*.jpg")
    )
    assert len(pages) == 5, f"{tower}: expected 5 plates, got {pages}"
    return pages


def plate_for_floor(tower: str, n: int, pages: list[int]) -> str | None:
    # Order per MEDIA-INTELLIGENCE doc: typical, refuge(7/15/22/29), fl36, duplex 39, duplex 40.
    if n == 13:
        return None  # full refuge floor, no residences
    if n in REFUGE_FLOORS:
        p = pages[1]
    elif n == 36 or (tower == "T02" and n in (37, 38)):
        p = pages[2]
    elif n == 39:
        p = pages[3]
    elif n == 40:
        p = pages[4]
    else:
        p = pages[0]
    return f"/dlf/{tower.lower()}-floor_plan-p{p}.jpg"


def config_plan_image(cfg: dict) -> str | None:
    matches = list(PUB.glob(f"*-p{cfg['floor_plan_page']}.jpg"))
    return f"/dlf/{matches[0].name}" if matches else None


def ts_str(s: str) -> str:
    return '"' + s.replace('"', '\\"') + '"'


towers_ts = []
for code, t in TOWERS.items():
    pages = plate_pages(code)
    cfgs = [c for c in UNIT_CONFIGS if c["tower_code"] == code]
    cfg_floors = {c["configuration_type"]: set(expand_floors(c["typical_floors"])) for c in cfgs}

    cfg_entries = []
    for c in cfgs:
        label = "Studio" if c["bhk"] == 1 else f"{c['bhk']} BHK"
        if "DUPLEX" in c["configuration_type"]:
            label += " Duplex"
        cfg_entries.append(
            "      {"
            f"id: {ts_str(c['configuration_type'])}, unit: {ts_str(c['unit_position'])}, "
            f"label: {ts_str(label)}, carpetSqft: {c['carpet_area_sqft']}, "
            f"balconySqft: {c['balcony_sqft']}, totalSqft: {c['total_area_sqft']}, "
            f"floors: {ts_str(c['typical_floors'])}, "
            f"planImage: {ts_str(config_plan_image(c) or '')}"
            "}"
        )

    floor_entries = []
    for n in range(3, t["floor_count"] + 1):
        on_floor = [ct for ct, fl in cfg_floors.items() if n in fl]
        kind = "refuge" if n == 13 else ("refuge-variant" if n in REFUGE_FLOORS else ("duplex" if n >= 39 else "typical"))
        plate = plate_for_floor(code, n, pages)
        floor_entries.append(
            "      {"
            f"n: {n}, kind: {ts_str(kind)}, "
            f"plate: {ts_str(plate) if plate else 'null'}, "
            f"configs: [{', '.join(ts_str(x) for x in on_floor)}]"
            "}"
        )

    towers_ts.append(
        "  {\n"
        f"    id: {ts_str(code)},\n"
        f"    name: {ts_str(t['tower_name'])},\n"
        f"    floorCount: {t['floor_count']},\n"
        "    configs: [\n" + ",\n".join(cfg_entries) + "\n    ],\n"
        "    floors: [\n" + ",\n".join(floor_entries) + "\n    ],\n"
        "  }"
    )

ts = f"""/**
 * DLF Westpark Phase 1 — floor & configuration data.
 * GENERATED by scripts/export_dlf_plans.py from seed_dlf_brochure_extraction.py
 * (source: visual review of the official brochure, Presenter 1.pdf). Do not hand-edit.
 * Plate→floor mapping (typical/refuge/fl36/duplex) inferred from brochure page order;
 * flag any mismatch to the operator.
 */

export const dlfProject = {{
  name: {ts_str(EXTRACTION["project_name"])},
  rera: {ts_str(EXTRACTION["rera_number"])},
  developer: {ts_str(EXTRACTION["developer_name"])},
  towers: {[*TOWERS.keys()]!r},
}} as const;

export interface DlfConfig {{
  id: string;
  unit: string;
  label: string;
  carpetSqft: number;
  balconySqft: number;
  totalSqft: number;
  floors: string;
  planImage: string;
}}

export interface DlfFloor {{
  n: number;
  kind: "typical" | "refuge" | "refuge-variant" | "duplex";
  plate: string | null;
  configs: string[];
}}

export interface DlfTower {{
  id: string;
  name: string;
  floorCount: number;
  configs: DlfConfig[];
  floors: DlfFloor[];
}}

export const dlfTowers: DlfTower[] = [
__TOWERS__,
];
"""
ts = ts.replace("__TOWERS__", ",\n".join(towers_ts))
# python repr of list isn't TS — fix towers list
ts = ts.replace("towers: ['T02', 'T03', 'T04', 'T05']!r,", 'towers: ["T02", "T03", "T04", "T05"],')
ts = ts.replace("towers: ['T02', 'T03', 'T04', 'T05'],", 'towers: ["T02", "T03", "T04", "T05"],')

OUT.write_text(ts)
n_floors = sum(len(t["floors"]) if isinstance(t, dict) else 0 for t in [])
print(f"wrote {OUT} ({len(UNIT_CONFIGS)} configs, {len(TOWERS)} towers)")

# self-check
assert "T05-STUDIO-01-REFUGE" in ts and "1260.72" in ts
print("self-check OK")
